feature_and_improvement: Implemented common exception handling and did some structural updates
hhsadiq/realworld-nestjs-medium-blog pull request #10
Opened 2024-08-28 12:20 UTC by AhmadHassanButt

**1. Generic Exception Handling**

1. Implemented a generic structure for handling exceptions.
2. Refactored the existing codebase to align with the new exception handling approach.

**2. Constants for Table Names**

1. Introduced a constants file dedicated to managing table names.
2. Updated existing references to table names to utilize the new constants.

**3. Domain Layer CamelCase Convention**

1. Updated the codebase to ensure the domain layer adheres to the camelCase naming convention.

**4. Hygen Template Updates**

1. Import Paths: Modified import paths to use absolute paths.
2. Exception Handling: Integrated the new common exception structure into Hygen templates.
3. Constants Management: Added support for managing constants within the Hygen templates.

**Summary**

This PR introduces several structural updates, including a generic exception handling mechanism, centralized table name constants, adherence to camelCase conventions in the domain layer, and improvements to Hygen templates.

2024-08-29 02:59 UTC, dev-ahmadbilal requested changes
@AhmadHassanButt Good work, just a quick suggestion for future PRs—it’s a good habit to break down changes into multiple commits. It helps make the history cleaner and easier to follow, especially when dealing with larger changes like this. No need to do it for this PR, but it would be great to see more granular commits in the future for better traceability and review. Thanks!

2024-08-29 02:59 UTC, dev-ahmadbilal commented on .hygen/generate/relational-resource/infrastructure/persistence/relational/entities/entity.ejs.t
> +import { TABLES } from '@src/common/constants';
Nice 👍

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/auth/auth.service.ts
> +      throw UNPROCESSABLE_ENTITY('password is not correct', 'password');
I noticed that the error message 'password is not correct' is used when the password is missing. It would be more accurate to update the message to something like 'password is not present' to better reflect the condition being checked.

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/auth/auth.service.ts
> +      throw UNPROCESSABLE_ENTITY('password is not correct', 'password');
I am noticing that error messages are hardcoded in the service. To improve maintainability and support for i18n, we should centralize such error messages. Consider defining these messages in a constants file. This approach will help with consistency across the application and make it easier to manage translations and modifications in the future.

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/users/users.service.ts
> +        throw UNPROCESSABLE_ENTITY('Email already exists', 'email');
I think the current exception `UNPROCESSABLE_ENTITY('Email already exists', 'email')` might not be the best fit for this scenario. Since the existence of the email typically indicates a constraint violation rather than a processing issue, it might be more appropriate to use a FORBIDDEN exception instead. This better communicates that the action (creating a user with an existing email) is not allowed due to an existing constraint.
`throw FORBIDDEN('Email already exists', 'email');`

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/users/users.service.ts
> +        throw UNPROCESSABLE_ENTITY('Image does not exist', 'photo');
`throw NOT_FOUND('Image does not exist', 'photo');`

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/users/users.service.ts
> +        throw UNPROCESSABLE_ENTITY('Role does not exist', 'role');
throw NOT_FOUND('Role does not exist', 'role');

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/users/users.service.ts
> +        throw UNPROCESSABLE_ENTITY('Status does not exist', 'status');
throw NOT_FOUND('Status does not exist', 'status');

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/users/users.service.ts
> +        throw UNPROCESSABLE_ENTITY('Email already exists', 'email');
`throw FORBIDDEN('Email already exists', 'email');`

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/users/users.service.ts
> +        throw UNPROCESSABLE_ENTITY('Image does not exist', 'photo');
^

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/users/users.service.ts
> +        throw UNPROCESSABLE_ENTITY('Role does not exist', 'role');
^

2024-08-29 02:59 UTC, dev-ahmadbilal commented on src/users/users.service.ts
> +        throw UNPROCESSABLE_ENTITY('Status does not exist', 'status');
^

2024-08-29 10:26 UTC, AhmadHassanButt commented
> @AhmadHassanButt Good work, just a quick suggestion for future PRs—it’s a good habit to break down changes into multiple commits. It helps make the history cleaner and easier to follow, especially when dealing with larger changes like this. No need to do it for this PR, but it would be great to see more granular commits in the future for better traceability and review. Thanks!

Thanks for the appreciation! I will keep your suggestion in my mind for the future PRs

2024-08-30 11:52 UTC, dev-ahmadbilal approved these changes
Looks good to me. Approving!

Cheers 🥂

2024-08-30 11:52 UTC, dev-ahmadbilal commented on src/auth/auth.service.ts
> +      throw UNAUTHORIZED('User not found with the valid role', 'role');
ERROR_MESSAGES*

2024-08-30 13:32 UTC, merged